Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.

    import numpy as np

    a = np.array([1,2,3,4], float)
    b = np.array([5,6,7,8], float)

    print(a + b)                     #[  6.   8.  10.  12.]
    print(np.add(a, b))              #[  6.   8.  10.  12.]

    print(a - b)                     #[-4. -4. -4. -4.]
    print(np.subtract(a, b))         #[-4. -4. -4. -4.]

    print(a * b)                     #[  5.  12.  21.  32.]
    print(np.multiply(a, b))         #[  5.  12.  21.  32.]

    print(a / b)                     #[ 0.2         0.33333333  0.42857143  0.5       ]
    print(np.divide(a, b))           #[ 0.2         0.33333333  0.42857143  0.5       ]

    print(a % b)                     #[ 1.  2.  3.  4.]
    print(np.mod(a, b))              #[ 1.  2.  3.  4.]

    print(a**b)                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
    print(np.power(a, b))            #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


In [1]:
import numpy as np

n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], int) for _ in range(2))

print(a+b , a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [4]:
a,b = 3,4

print(a/b)
print(a//b)

0.75
0
